gems: ['jekyll-paginate']

# Site Settings
title: 						"Anthony Lee"
email: 						"hi@anthonylee.io"
description: 				"My name is Anthony. I am a developer from Colorado. I love to code and better the world."
baseurl:          ""
blogurl:          "/blog"
logourl: 					"/assets/img/anthonylee.png"
fa-logo: 					"fa-bookmark-o"
paginate: 3
paginate_path: "/blog/page:num/"

  # Author Settings
author_name: 				"Anthony Lee"
author_url: 				"http://anthonylee.io"
author_bio: 				"I love Ruby, Rails, TDD, Vim, Javascript, Apex (Force.com), jazz guitar, craft beer and coffee."
author_email: 				"hi@anthonylee.io"
author_image: 				"/assets/img/anthonylee.png"

  # Social Settings
twitter_url:        "https://twitter.com/anthonygawonlee"
facebook_url:         ""
github_url:         "http://github.com/antwonlee"
youtube_url:          "https://www.youtube.com/user/anthonygawonlee/videos"
dribbble_url:         "http://dribbble.com/anthonylee"
googleplus_url:       ""
instagram_url:        ""
pinterest_url:        ""
linkedin_url:         ""

  # Theme Settings
theme_disqus_shortname: 	"anthonyleeio"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 	 false

  # SASS Settings
  # DO NOT MODIFY
sass:
  sass_dir: "assets/css/"
style: :compressed

  # Build Settings
markdown: 					kramdown
permalink: 					:year/:month/:day/:title/
