# Site settings
title: Anthony Lee - Software Developer
email: hi@anthonylee.io
description: My name is Anthony. I am a developer from Colorado. I love to code and better the world.
url: "http://anthonylee.io"
twitter_username: anthonygawonlee
github_username:  antwonlee

# Build settings
markdown: kramdown
permalink: pretty
